
package informacionAcademy;

import java.awt.Image;
import principalAcademy.Pagar;
import principalAcademy.QRpagar;
import principalAcademy.frmlogin;
 import javax.swing.*; 



public class informacion extends javax.swing.JFrame {
    public static frmlogin frm;
     public static QRpagar pa;
    
    public informacion() {
        initComponents();
         setLocationRelativeTo(null); //centrado de la ventana
        
        //Dimension de imagenes
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/proceso1.PNG"));
         ImageIcon imagen2=new ImageIcon(getClass().getResource("/imagenes/proceso2.PNG"));
         ImageIcon imagen3=new ImageIcon(getClass().getResource("/imagenes/yape.PNG"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(imagD1.getWidth(),imagD1.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo2= new ImageIcon(imagen2.getImage().getScaledInstance(imagD2.getWidth(),imagD2.getHeight(), Image.SCALE_DEFAULT));
        Icon fondo3= new ImageIcon(imagen3.getImage().getScaledInstance(imagD3.getWidth(),imagD3.getHeight(), Image.SCALE_DEFAULT));
        imagD1.setIcon(fondo1);
        imagD2.setIcon(fondo2);
        imagD3.setIcon(fondo3);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtatras = new javax.swing.JButton();
        txtatras1 = new javax.swing.JButton();
        imagD2 = new javax.swing.JLabel();
        imagD1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imagD3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(198, 184, 184));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtatras.setBackground(new java.awt.Color(102, 102, 255));
        txtatras.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtatras.setText("Atras");
        txtatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtatrasActionPerformed(evt);
            }
        });
        jPanel1.add(txtatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 394, 91, -1));

        txtatras1.setBackground(new java.awt.Color(102, 102, 255));
        txtatras1.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        txtatras1.setText("Pague Aquí");
        txtatras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtatras1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtatras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 394, 151, -1));

        imagD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proceso2.PNG"))); // NOI18N
        jPanel1.add(imagD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 200, 240));

        imagD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proceso1.PNG"))); // NOI18N
        jPanel1.add(imagD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 238, 315));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setText("Pague Aquí desde tu billetera didital Yape");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 490, -1));

        imagD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/yape.PNG"))); // NOI18N
        jPanel1.add(imagD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("9577788888");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtatrasActionPerformed
        
        dispose();
         frm=new frmlogin(null,true); //realiza llamado de ventana
       frm.setVisible(true); //el llamado ventana se visualiza
        
    }//GEN-LAST:event_txtatrasActionPerformed

    private void txtatras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtatras1ActionPerformed
         dispose();
                       pa=new QRpagar(null,true); //realiza llamado de ventana
                        pa.setVisible(true); //
        
    }//GEN-LAST:event_txtatras1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagD1;
    private javax.swing.JLabel imagD2;
    private javax.swing.JLabel imagD3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txtatras;
    private javax.swing.JButton txtatras1;
    // End of variables declaration//GEN-END:variables
}
