/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package informacionAcademy;
 import java.sql.Connection;
//import com.mysql.jdbc.Connection;

import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import conectarbd.*;
import java.awt.Image;

 import javax.swing.*; 

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import principalAcademy.frmlogin;
/**
 *
 * @author DELL
 */
public class intranetAdministrador extends javax.swing.JFrame {
        
    conectarbd.conexionMysql con=new conexionMysql(); //coneccion con bases de datos
    Connection cn=(Connection) con.conectar();
    
    public  String DNIadminLog;
    
    public intranetAdministrador() {
        initComponents();
         setLocationRelativeTo(null); //centrado de ventana principal
        mostrarTablaEstu("");  
        
         ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/imglogin.png"));
         
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(logadmi.getWidth(),logadmi.getHeight(), Image.SCALE_DEFAULT));
        
        logadmi.setIcon(fondo1);
        
        
        
        this.repaint();
        
    }
    
    Metodos_sql metodos = new Metodos_sql(); //instanciamos  clase Metodos_sql

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logadmi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaDatosAdmin = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        DNIadmin = new javax.swing.JTextField();
        txtNomAdmin = new javax.swing.JTextField();
        txtApelAdmin = new javax.swing.JTextField();
        txtsexoAdmin = new javax.swing.JTextField();
        txtCorrAdmin = new javax.swing.JTextField();
        txtCellAdmin = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtADname = new javax.swing.JTextField();
        txtAdminContra = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtdnies = new javax.swing.JTextField();
        comboob = new javax.swing.JComboBox<>();
        txtdeuda = new javax.swing.JTextField();
        txtfecan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        comboDeudores = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosDeudoresss = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        txtgrupoos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableGrupos = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEstudiante = new javax.swing.JTable();
        txtCorreoAlm = new javax.swing.JTextField();
        txtCelularAlum = new javax.swing.JTextField();
        txtDNIalum = new javax.swing.JTextField();
        txtSexoAlum = new javax.swing.JTextField();
        txtApellidoAlum = new javax.swing.JTextField();
        txtNombreAlum = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtcodRepor = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtcicloRepor = new javax.swing.JTextField();
        txtnombreCM = new javax.swing.JTextField();
        txtcodcons = new javax.swing.JTextField();
        txtnombreCMtxt = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        logRepor = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(121, 48, 48));
        jButton9.setText("Cerrar Sesión");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 110, -1));

        jPanel2.setBackground(new java.awt.Color(179, 126, 126));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logadmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imglogin.png"))); // NOI18N
        jPanel2.add(logadmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 100));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/adm3.PNG"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 160));

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel11.setText("Estudiantes Matriculados");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 30));

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel10.setText("Estudiantes Por Grupo");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, 30));

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel9.setText("Estudiantes con Deuda");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, 30));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel8.setText("Registrar Estudiantes");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 30));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel7.setText("Cambiar mi Contraseña");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel6.setText("Mis Datos Personales");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 30));

        jPanel26.setBackground(new java.awt.Color(179, 126, 126));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 13)); // NOI18N
        jLabel5.setText("       ADMINISTRADOR");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 30));

        jLabel2.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        jLabel2.setText("Generar Reportes");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 210, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admi2.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 600, 90));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBackground(new java.awt.Color(193, 161, 161));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 427));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel31.setBackground(new java.awt.Color(193, 161, 161));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDatosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaDatosAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosAdminMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaDatosAdmin);

        jPanel31.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 580, 70));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel31.setText("N° DNI:");
        jPanel22.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        jLabel32.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel32.setText("Nombres:");
        jPanel22.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel33.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel33.setText("Apellidos:");
        jPanel22.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        jLabel34.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel34.setText("Sexo:");
        jPanel22.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        jLabel35.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel35.setText("E-mail:");
        jPanel22.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));

        DNIadmin.setEditable(false);
        DNIadmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(DNIadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, 30));

        txtNomAdmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(txtNomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 30));

        txtApelAdmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(txtApelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 180, 30));

        txtsexoAdmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(txtsexoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 30));

        txtCorrAdmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(txtCorrAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 180, 30));

        txtCellAdmin.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel22.add(txtCellAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 180, 30));

        jLabel36.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel36.setText("N° Celular:");
        jPanel22.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        jPanel31.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 280));

        jPanel32.setBackground(new java.awt.Color(204, 204, 204));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(117, 10, 10));
        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(117, 10, 10));
        jLabel37.setText("Mis Datos");
        jPanel32.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, -1));

        jPanel31.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 170, 170));

        jButton7.setText("Editar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel31.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 110, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel33.setBackground(new java.awt.Color(201, 177, 177));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAdminMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tableAdmin);

        jPanel33.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 330, 540, 80));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel38.setText("Usuario");
        jPanel23.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        jLabel40.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel40.setText("Contraseña");
        jPanel23.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));

        txtADname.setEditable(false);
        txtADname.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel23.add(txtADname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 40));

        txtAdminContra.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel23.add(txtAdminContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 170, 40));

        jPanel33.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 340, 230));

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel33.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 180, 120));

        jButton8.setText("Cambiar Contraseña");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel33.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 180, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(117, 10, 10));
        jLabel41.setText("CONFIGURACIÓN DE CONTRASEÑA");
        jPanel33.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 370, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(224, 204, 204));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(117, 10, 10));
        jLabel13.setText("DIGITAR LOS DATOS DE LOS ESTUDIANTES QUE REALIZARON PAGO DE MATRICULA");
        jPanel27.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 580, 40));

        txtdnies.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jPanel27.add(txtdnies, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 170, 40));

        comboob.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        comboob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Cancelado", "Tiene_Deuda" }));
        jPanel27.add(comboob, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 170, 40));

        txtdeuda.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jPanel27.add(txtdeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 40));

        txtfecan.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jPanel27.add(txtfecan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 170, 40));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setText("N° DNI de Estudiante");
        jPanel27.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 30));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setText("Observaciones");
        jPanel27.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 140, 30));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setText("Deuda de Estudiante");
        jPanel27.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 170, 20));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setText("N° Celular");
        jPanel27.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton1.setText("Registrar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 170, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n     \n\n     Revise el aplicativo\n     yape de la academia\n     y registre los datos \n     de los estudiantes\n     que realizaron su \n     pago correspondiente\n     de la matricula");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel27.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 280));

        jPanel6.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(198, 183, 183));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboDeudores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Tiene_Deuda", "Cancelado" }));
        jPanel25.add(comboDeudores, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 24, 190, 40));

        jButton2.setText("Ver Listado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 33, 124, -1));

        jLabel30.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel30.setText("Seleccione la opción");
        jPanel25.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 150, -1));

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 560, 80));

        datosDeudoresss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(datosDeudoresss);

        jPanel24.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 560, 210));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(117, 10, 10));
        jLabel19.setText("LISTADO DE ESTUDIANTES CON DEUDA O SIN DEUDA");
        jPanel24.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 20, 530, 30));

        jPanel7.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBackground(new java.awt.Color(153, 153, 153));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel20.setText("Digite un grupo A, B, C o D");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtgrupoos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgrupoos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel20))
                .addGap(25, 25, 25))
        );

        jPanel29.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 550, 80));

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(117, 10, 10));
        jLabel21.setText("LISTADO DE ESTUDIANTES POR GRUPO ");
        jPanel29.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 440, -1));

        tableGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableGrupos);

        jPanel29.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 550, 200));

        jPanel8.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane1.addTab("tab6", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel30.setBackground(new java.awt.Color(193, 161, 161));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEstudianteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableEstudiante);

        jPanel30.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 580, 150));
        jPanel30.add(txtCorreoAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, -1));
        jPanel30.add(txtCelularAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 190, -1));

        txtDNIalum.setEditable(false);
        jPanel30.add(txtDNIalum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 190, -1));
        jPanel30.add(txtSexoAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, -1));
        jPanel30.add(txtApellidoAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 190, -1));
        jPanel30.add(txtNombreAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, -1));

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, -1));

        jButton6.setText("Borrar");
        jPanel14.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel14.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, -1));

        jLabel12.setText("Buscar");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel30.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 200, 180));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel23.setText("E-mail");
        jPanel30.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel24.setText("N° Celular");
        jPanel30.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, -1));

        jLabel25.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel25.setText("N°  DNI");
        jPanel30.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jLabel26.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel26.setText("Sexo");
        jPanel30.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));

        jLabel27.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel27.setText("Apellidos");
        jPanel30.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, -1));

        jLabel28.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel28.setText("Nombre");
        jPanel30.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(117, 10, 10));
        jLabel29.setText("ACTUALIZAR DATOS DE LOS ESTUDIANTES");
        jPanel30.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 450, 30));

        jPanel9.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 430));

        jTabbedPane1.addTab("tab7", jPanel9);

        jPanel10.setBackground(new java.awt.Color(187, 140, 140));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel43.setText("GENERE REPORTE SOLICITADO");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        jLabel44.setText("Digite N° DNI de Alumno:");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, -1));
        jPanel10.add(txtcodRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, 30));

        jPanel37.setBackground(new java.awt.Color(217, 207, 207));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(166, 113, 113));
        jButton10.setText("Constancia de Matrícula");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 32, 180, 30));

        jButton11.setBackground(new java.awt.Color(166, 113, 113));
        jButton11.setText("Constancia de Notas");
        jPanel37.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 189, 30));

        jButton12.setBackground(new java.awt.Color(166, 113, 113));
        jButton12.setText("Constancia de Estudio");
        jPanel37.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 74, 182, 30));

        jPanel10.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 240, 190));

        jTabbedPane1.addTab("tab8", jPanel10);

        jPanel36.setBackground(new java.awt.Color(187, 140, 140));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab12", jPanel36);

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel45.setText("CONSTANCIA DE MATRÍCULA");
        jPanel38.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 240, -1));

        jLabel46.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel46.setText("Fecha de Matrícula      :");
        jPanel38.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, -1));

        jLabel47.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel47.setText("Estudiante                      :");
        jPanel38.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        jLabel48.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel48.setText("Código                            :");
        jPanel38.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 140, -1));

        jLabel49.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel49.setText("Ciclo                                :");
        jPanel38.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(null);
        jPanel38.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, 20));

        txtcicloRepor.setEditable(false);
        txtcicloRepor.setBackground(new java.awt.Color(255, 255, 255));
        txtcicloRepor.setBorder(null);
        jPanel38.add(txtcicloRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 190, 20));

        txtnombreCM.setEditable(false);
        txtnombreCM.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreCM.setBorder(null);
        jPanel38.add(txtnombreCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, 20));

        txtcodcons.setEditable(false);
        txtcodcons.setBackground(new java.awt.Color(255, 255, 255));
        txtcodcons.setBorder(null);
        jPanel38.add(txtcodcons, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 190, 20));

        txtnombreCMtxt.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtnombreCMtxt.setBorder(null);
        jPanel38.add(txtnombreCMtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 20));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Rockwell", 2, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\t\n            Que, el estudiate                                                   , \nse encuentra en nuestra ACADEMIA PITÁGORAS, cuyo inicio\nde clases es en el mes de Marzo del presente año\nlectivo; cuya duración es de de 4 meses.");
        jScrollPane8.setViewportView(jTextArea3);

        jPanel38.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 470, 150));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lineaFir.PNG"))); // NOI18N
        jPanel38.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 200, 10));

        jLabel51.setText("Dirección de Gestión Académica");
        jPanel38.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        logRepor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sigla.PNG"))); // NOI18N
        jPanel38.add(logRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, 50));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fleAtrs.PNG"))); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel53MouseClicked(evt);
            }
        });
        jPanel38.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab9", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab10", jPanel12);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab11", jPanel13);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 600, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 826, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
      jTabbedPane1.setSelectedIndex(0);  // cuando se da click llama a jpanel:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       jTabbedPane1.setSelectedIndex(1); // TODO add your handling code here:
       mostrarDatosAdmin();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       jTabbedPane1.setSelectedIndex(2); // TODO add your handling code here:
       mostrarTadmin();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       jTabbedPane1.setSelectedIndex(3); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
      jTabbedPane1.setSelectedIndex(4);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
      jTabbedPane1.setSelectedIndex(5);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
      jTabbedPane1.setSelectedIndex(6);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String dniestu=txtdnies.getText();
        String observaciones=comboob.getSelectedItem().toString();
        String deudas = txtdeuda.getText();
        String NCelular = txtfecan.getText();
        //String dniAdmin=txtdniad.getText();
        
        
        if(dniestu.isEmpty()|| deudas.isEmpty()){
          JOptionPane.showMessageDialog(null,"DEBE COMPLETAR LOS DATOS"); // manda mensaje cuando el formulario esta vacio
        }else{
            if(observaciones.equalsIgnoreCase("----")){
                JOptionPane.showMessageDialog(null,"DEBE SELECCIONAR UN GRUPO");
            }else{
                
                try{ 
                    String consulta="INSERT INTO tdetalle_estudiante(DNI_E, observacion, deuda) VALUES ('"+dniestu+"','"+observaciones+"','"+deudas+"')";
                    PreparedStatement ps=(PreparedStatement) cn.prepareStatement(consulta);
                    ps.executeUpdate();
                   
                    { String consulta1="INSERT INTO tusuario(u_dni, password) VALUES ('"+dniestu+"','"+NCelular+"')";
                   PreparedStatement pt=(PreparedStatement) cn.prepareStatement(consulta1);
                    pt.executeUpdate();}
                    
                    
                    limpiar(); // llama a metodo limpiar
                    JOptionPane.showMessageDialog(null,"DATOS GUARDADOS CORRECTAMENTE");
                } catch (Exception e){
                     JOptionPane.showMessageDialog(null,"NO SE PUDO INGRESAR DATOS"+e);
                    
                }
            }
               
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      mostrarTablaGrupo();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      mostrarTablaEstu(txtBuscar.getText());
                    // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarTablaEstu("");
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEstudianteMouseClicked
        Modificar();  // TODO add your handling code here:
    }//GEN-LAST:event_tableEstudianteMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

           ModificarDatos();        // TODO add your handling code here:  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      mostrarTablaDeudos();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablaDatosAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosAdminMouseClicked
       ModificarDaAdmin(); // TODO add your handling code here:  AAAAAAAAAAAAA
    }//GEN-LAST:event_tablaDatosAdminMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ModificarDatosAdmin();
       // ModificarDaAdmin();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tableAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAdminMouseClicked
        ModificarADtrasenia();        // TODO add your handling code here:
    }//GEN-LAST:event_tableAdminMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            ModificarAdminContrase();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dispose();  // la ventana anterior se cierra
       frmlogin dialog = new frmlogin(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       jTabbedPane1.setSelectedIndex(7); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       jTabbedPane1.setSelectedIndex(9); 
       // TODO add your handling code here:
       String busqueda_nombre =metodos.buscarNombreRepor(txtcodRepor.getText());   
                       txtnombreCM.setText(busqueda_nombre);  // muestra el nombre de navegador
                       txtnombreCMtxt.setText(busqueda_nombre);
                       
                       txtcodcons.setText(txtcodRepor.getText());
        String busqueda_ciclo =metodos.buscarNombreReporCiclo(txtcodRepor.getText());               
                    txtcicloRepor.setText(busqueda_ciclo); 
        
        String busqueda_fecha =metodos.buscarNombreReporFecha(txtcodRepor.getText());               
                    jTextField2.setText(busqueda_fecha);
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseClicked
        jTabbedPane1.setSelectedIndex(7); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel53MouseClicked

    void limpiar(){ //borra despues de haber registrado
        txtdnies.setText("");
        txtdeuda.setText("");
        comboob.getSelectedItem().toString();
        txtfecan.setText("");
       // txtdniad.setText("");
        
    }
    
    ////////////////////////////////////////////////////////////////////////////////////////
    void mostrarTablaDeudos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("N° DNI");
        modelo.addColumn("N° Celular");
        modelo.addColumn("Observación");
        modelo.addColumn("Deuda");
        //modelo.addColumn("FechaCancelar");
        datosDeudoresss.setModel(modelo);
        
        String sql = "SELECT a.nombres, a.apellidos, a.DNI_E, a.celular, d.observacion, d.deuda \n" +
               "FROM talumno as a INNER JOIN tdetalle_estudiante as d on a.DNI_E=d.DNI_E WHERE d.observacion = '"+comboDeudores.getSelectedItem().toString()+"'";
        String datos[] = new String [7];
        Statement st;
        try{
            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
               
                modelo.addRow(datos);
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    /////////////////////////////////////////////////////////////////////////////////////////
    void mostrarTablaGrupo(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("N° DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Sexo");
        modelo.addColumn("N° Celular");
        modelo.addColumn("Grupo");
        modelo.addColumn("E-mail");
        tableGrupos.setModel(modelo);
        
        String sql = "SELECT a.DNI_E, a.nombres, a.apellidos, a.sexo, a.celular, m.grupo, a.correo \n" +
               "FROM talumno as a INNER JOIN tmatricula as m on a.DNI_E=m.codigoAlumno WHERE m.grupo like '"+txtgrupoos.getText()+"'";
        String datos[] = new String [8];
        Statement st;
        try{
            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                datos[3]=rs.getString(4);
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(7);
                modelo.addRow(datos);
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
   
    
    void mostrarTablaEstu(String Nombre){
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("N° DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Sexo");
        //modelo.addColumn("N° DNI");
        modelo.addColumn("N° Celular");
        modelo.addColumn("E-mail");
        tableEstudiante.setModel(modelo);
        
        String sql="";
        if(Nombre.equals("")){
            sql="SELECT * FROM  talumno";
        }else{
            sql="Select*from talumno where Nombre like'%"+Nombre+"%'";
        }
        String Usuario[]=new String[7];
        Statement set;
        
        try{
           set =(Statement) cn.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()){
                Usuario[0]=resul.getString(1);
                Usuario[1]=resul.getString(2);
                Usuario[2]=resul.getString(3);
                Usuario[3]=resul.getString(4);
                Usuario[4]=resul.getString(5);
                Usuario[5]=resul.getString(6);
                
                modelo.addRow(Usuario);
            }
          tableEstudiante.setModel(modelo);  
        }catch(Exception e){
        System.out.println(e.getMessage());    
        //Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void Modificar(){
        int fila=tableEstudiante.getSelectedRow();
        if(fila>=0){
            txtDNIalum.setText(tableEstudiante.getValueAt(fila,0).toString());
            txtNombreAlum.setText(tableEstudiante.getValueAt(fila,1).toString());
            txtApellidoAlum.setText(tableEstudiante.getValueAt(fila,2).toString());
            txtSexoAlum.setText(tableEstudiante.getValueAt(fila,3).toString());
            txtCelularAlum.setText(tableEstudiante.getValueAt(fila,4).toString());
            txtCorreoAlm.setText(tableEstudiante.getValueAt(fila,5).toString());
           
                    
        }
        else{
            JOptionPane.showConfirmDialog(null,"Seleccione fila");
        }
        
    }
    
    public void ModificarDatos(){
        try{
        PreparedStatement pasar=(PreparedStatement) cn.prepareStatement("Update talumno set nombres='"+txtNombreAlum.getText()+"',apellidos='"+txtApellidoAlum.getText()+"',sexo='"+txtSexoAlum.getText()+"',celular='"+txtCelularAlum.getText()+"',correo='"+txtCorreoAlm.getText()+"'where DNI_E='"+txtDNIalum.getText()+"'");
       pasar.executeUpdate();
       mostrarTablaEstu("");
       
        }catch (SQLException ex) {
          
        }
    }
        
    //muestra datos de admistrador en la TablaMisDatosEst py permite editar
    void mostrarDatosAdmin(){  
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("N° DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Sexo");
        modelo.addColumn("N° Celular");
        modelo.addColumn("E-mail");
        tablaDatosAdmin.setModel(modelo);
        
          String  sql="Select*from tpersonal_academy where DNI_A  = '"+DNIadminLog+"'";

        String Usuario[]=new String[6];
        Statement set;
        
        try{
           set =(Statement) cn.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()){
                Usuario[0]=resul.getString(1);
                Usuario[1]=resul.getString(2);
                Usuario[2]=resul.getString(3);
                Usuario[3]=resul.getString(4);
                Usuario[4]=resul.getString(5);
                Usuario[5]=resul.getString(6);
                modelo.addRow(Usuario);
            }
           
        }catch(Exception e){
        System.out.println(e.getMessage());    
        //Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }  
    } 
    
// Modificador
    public void ModificarDaAdmin(){
        int fila=tablaDatosAdmin.getSelectedRow();
        if(fila>=0){
            DNIadmin.setText(tablaDatosAdmin.getValueAt(fila,0).toString());
            txtNomAdmin.setText(tablaDatosAdmin.getValueAt(fila,1).toString());
            txtApelAdmin.setText(tablaDatosAdmin.getValueAt(fila,2).toString());
            txtsexoAdmin.setText(tablaDatosAdmin.getValueAt(fila,3).toString());
            txtCellAdmin.setText(tablaDatosAdmin.getValueAt(fila,4).toString());
            txtCorrAdmin.setText(tablaDatosAdmin.getValueAt(fila,5).toString());
                    
        }
        else{
            JOptionPane.showConfirmDialog(null,"Seleccione fila");
        }   
    }
    
    //
     public void ModificarDatosAdmin(){
    
        try{
        PreparedStatement pasar=(PreparedStatement) cn.prepareStatement("Update tpersonal_academy set nombres='"+txtNomAdmin.getText()+""+
                "',apellidos='"+txtApelAdmin.getText()+"',sexo='"+txtsexoAdmin.getText()+"',celular='"+txtCellAdmin.getText()+""+
                        "',correo='"+txtCorrAdmin.getText()+"'where DNI_A='"+DNIadmin.getText()+"'");
       pasar.executeUpdate();
       mostrarDatosAdmin();
       
        }catch (SQLException ex) {
          
        }
    }
    
    //muestra la tabla para edicion de contraseña DEL administracion
    void mostrarTadmin(){  
        DefaultTableModel modelo=new DefaultTableModel();
        
        modelo.addColumn("USUARIO");
        modelo.addColumn("CONTRASEÑA");
      
        tableAdmin.setModel(modelo);
        
          String  sql="SELECT u_dni, password FROM tusuario  WHERE u_dni = '"+DNIadminLog+"'";

        String Usuario[]=new String[3];
        Statement set;
        
        try{
           set =(Statement) cn.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()){
                Usuario[0]=resul.getString(1);
                Usuario[1]=resul.getString(2);
               
                
                modelo.addRow(Usuario);
            }
        }catch(Exception e){
        System.out.println(e.getMessage());    
        //Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    //
     public void ModificarADtrasenia(){
        int fila=tableAdmin.getSelectedRow();
        if(fila>=0){
            
            txtADname.setText(tableAdmin.getValueAt(fila,0).toString());
            txtAdminContra.setText(tableAdmin.getValueAt(fila,1).toString());
                   
        }
        else{
            JOptionPane.showConfirmDialog(null,"Seleccione fila");
        }   
    }
    
    //Modificar la contraseña de Administrador
     public void ModificarAdminContrase(){
    
        try{
        PreparedStatement pasar=(PreparedStatement) cn.prepareStatement("Update tusuario set password='"+txtAdminContra.getText()+""+
                        "'where u_dni = '"+txtADname.getText()+"'");
       pasar.executeUpdate();
       mostrarTadmin();
       
        }catch (SQLException ex) {
          
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intranetAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intranetAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intranetAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intranetAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intranetAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNIadmin;
    private javax.swing.JComboBox<String> comboDeudores;
    private javax.swing.JComboBox<String> comboob;
    private javax.swing.JTable datosDeudoresss;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel logRepor;
    private javax.swing.JLabel logadmi;
    private javax.swing.JTable tablaDatosAdmin;
    private javax.swing.JTable tableAdmin;
    private javax.swing.JTable tableEstudiante;
    private javax.swing.JTable tableGrupos;
    private javax.swing.JTextField txtADname;
    private javax.swing.JTextField txtAdminContra;
    private javax.swing.JTextField txtApelAdmin;
    private javax.swing.JTextField txtApellidoAlum;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCellAdmin;
    private javax.swing.JTextField txtCelularAlum;
    private javax.swing.JTextField txtCorrAdmin;
    private javax.swing.JTextField txtCorreoAlm;
    private javax.swing.JTextField txtDNIalum;
    private javax.swing.JTextField txtNomAdmin;
    private javax.swing.JTextField txtNombreAlum;
    private javax.swing.JTextField txtSexoAlum;
    private javax.swing.JTextField txtcicloRepor;
    private javax.swing.JTextField txtcodRepor;
    private javax.swing.JTextField txtcodcons;
    private javax.swing.JTextField txtdeuda;
    private javax.swing.JTextField txtdnies;
    private javax.swing.JTextField txtfecan;
    private javax.swing.JTextField txtgrupoos;
    private javax.swing.JTextField txtnombreCM;
    private javax.swing.JTextField txtnombreCMtxt;
    private javax.swing.JTextField txtsexoAdmin;
    // End of variables declaration//GEN-END:variables
}
