/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package informacionAcademy;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import conectarbd.*;
import java.awt.Image;
//import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import principalAcademy.frmlogin;
import java.sql.SQLException;

import javax.swing.*; 
/**
 *
 * @author DELL
 */
public class intranetEstudiante extends javax.swing.JFrame {
    public static frmlogin fmrlog;
        
    conectarbd.conexionMysql con=new conexionMysql(); //coneccion con bases de datos
    Connection cn=con.conectar(); 
    
   public  String DNIusuarioLog;
    
    
    public intranetEstudiante() {
        initComponents();
        mostrarTablaEstud();
         setLocationRelativeTo(null); //centrado de ventana principal
         
         ImageIcon imagen1=new ImageIcon(getClass().getResource("/imagenes/fonsup.jpeg"));
        Icon fondo1= new ImageIcon(imagen1.getImage().getScaledInstance(fonsup1.getWidth(),fonsup1.getHeight(), Image.SCALE_DEFAULT));
        fonsup1.setIcon(fondo1);
        this.repaint();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        activoUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        fonsup1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Pane1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Pane2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMisDatosEst = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        txtMyCorreo = new javax.swing.JTextField();
        txtMyCell = new javax.swing.JTextField();
        txtMyDNI = new javax.swing.JTextField();
        txtMySex = new javax.swing.JTextField();
        txtmiApelli = new javax.swing.JTextField();
        txtmiName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Pane3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMyContrase = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtUserContra = new javax.swing.JTextField();
        txtaUsename = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Pane4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox<>();
        txtdni = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Pane5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        Pane6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        combotipog = new javax.swing.JComboBox<>();
        combotipot = new javax.swing.JComboBox<>();
        combotipoc = new javax.swing.JComboBox<>();
        txtNdni = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(112, 156, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginIMA.PNG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 100));

        activoUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jPanel1.add(activoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoA.PNG"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 150));

        jPanel2.setBackground(new java.awt.Color(112, 156, 228));

        jLabel9.setBackground(new java.awt.Color(190, 210, 233));
        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel9.setText("        ESTUDIANTE");
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jLabel9.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jLabel9VetoableChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, 30));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("Mis Datos Personales");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("Cambiar mi Contraseña");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 30));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Ingresa a Matrícularte");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, 30));

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Cerrar Sesión");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 480));

        fonsup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fonsup.jpeg"))); // NOI18N
        getContentPane().add(fonsup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 610, 80));

        jPanel13.setBackground(new java.awt.Color(190, 210, 233));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(23, 37, 204));
        jLabel10.setText("ACADEMIA PITAGORAS");
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 242, 35));

        javax.swing.GroupLayout Pane1Layout = new javax.swing.GroupLayout(Pane1);
        Pane1.setLayout(Pane1Layout);
        Pane1Layout.setHorizontalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        Pane1Layout.setVerticalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Pane1);

        Pane2.setBackground(new java.awt.Color(190, 210, 233));
        Pane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(190, 210, 233));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(112, 156, 228));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel4.setText("Mis Datos");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 200, 140));

        TablaMisDatosEst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaMisDatosEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMisDatosEstMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaMisDatosEst);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 550, 70));

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 120, 30));

        txtMyCorreo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel7.add(txtMyCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 200, 30));

        txtMyCell.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel7.add(txtMyCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 30));

        txtMyDNI.setEditable(false);
        txtMyDNI.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel7.add(txtMyDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, 30));

        txtMySex.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtMySex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMySexActionPerformed(evt);
            }
        });
        jPanel7.add(txtMySex, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 30));

        txtmiApelli.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        txtmiApelli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmiApelliActionPerformed(evt);
            }
        });
        jPanel7.add(txtmiApelli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, 30));

        txtmiName.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel7.add(txtmiName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 200, 30));

        jLabel26.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel26.setText("E-mail:");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 30));

        jLabel27.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel27.setText("N° Celular:");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 30));

        jLabel28.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel28.setText("N° DNI:");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, 30));

        jLabel29.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel29.setText("Sexo:");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        jLabel30.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel30.setText("Apellidos:");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 110, 30));

        jLabel31.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel31.setText("Nombres:");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 30));

        Pane2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("tab2", Pane2);

        Pane3.setBackground(new java.awt.Color(190, 210, 233));
        Pane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(190, 210, 233));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 210, 100));

        tableMyContrase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableMyContrase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMyContraseMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableMyContrase);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 560, 70));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel34.setText("Contraseña:");
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 30));

        txtUserContra.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel11.add(txtUserContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 191, 40));

        txtaUsename.setEditable(false);
        txtaUsename.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jPanel11.add(txtaUsename, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 191, 40));

        jLabel36.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jLabel36.setText("Usuario:");
        jPanel11.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 330, 210));

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 153));
        jLabel35.setText("CONFIGORACION DE CONTRASEÑA");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 360, 30));

        jButton4.setText("Cambiar Contraseña");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 170, 30));

        Pane3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("tab3", Pane3);

        Pane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(190, 210, 233));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("DATOS PERSONALES");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 270, 40));

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setText("Nombres");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setText("Apellidos");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setText("Sexo");
        jPanel14.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel17.setText("DNI:");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel18.setText("N° Celular");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setText("E-mail");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        txtnombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombresActionPerformed(evt);
            }
        });
        jPanel14.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 220, 30));

        txtapellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel14.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 220, 30));

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----", "M", "F" }));
        jPanel14.add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 220, 30));

        txtdni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel14.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 220, 30));

        txtcelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel14.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 220, 30));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel14.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 220, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 140, 30));

        Pane4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 407));

        jTabbedPane1.addTab("tab4", Pane4);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Pane5Layout = new javax.swing.GroupLayout(Pane5);
        Pane5.setLayout(Pane5Layout);
        Pane5Layout.setHorizontalGroup(
            Pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Pane5Layout.setVerticalGroup(
            Pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", Pane5);

        Pane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(190, 210, 233));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("DATOS DE MATRÍCULA");
        jPanel15.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 230, 40));

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel21.setText("Grupo:");
        jPanel15.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel22.setText("Turno:");
        jPanel15.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel23.setText("Ciclo:");
        jPanel15.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel24.setText("Código o DNI");
        jPanel15.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        combotipog.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        combotipog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "A", "B", "C", "D" }));
        jPanel15.add(combotipog, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 180, 40));

        combotipot.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        combotipot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Mañana", "Tarde" }));
        jPanel15.add(combotipot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 180, 40));

        combotipoc.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        combotipoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "Ordinario", "Primera Opción" }));
        jPanel15.add(combotipoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, 40));

        txtNdni.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jPanel15.add(txtNdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 180, 40));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jButton2.setText("Registrar Matrícula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 321, -1, 30));

        Pane6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 407));

        jTabbedPane1.addTab("tab6", Pane6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jTabbedPane1.setSelectedIndex(1);
       mostrarTablaEstud();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jTabbedPane1.setSelectedIndex(2);
        mostrarTUsername();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String dni=txtdni.getText();
       // String codigo=txtcodigo.getText();
        String nombres=txtnombres.getText();
        String apellidos=txtapellidos.getText();
        String sexo=combotipo.getSelectedItem().toString();
        
        String celular=txtcelular.getText();
        String email=txtemail.getText();
        
       
        
        if(dni.isEmpty()||nombres.isEmpty()|| apellidos.isEmpty()||celular.isEmpty()||email.isEmpty()){
          JOptionPane.showMessageDialog(null,"DEBE COMPLETAR LOS DATOS"); // manda mensaje cuando el formulario esta vacio
        }else{
            if(sexo.equalsIgnoreCase("-----")){
                JOptionPane.showMessageDialog(null,"DEBE SELECCIONAR UN GRUPO");
            }else{
                try{
                    String consulta="INSERT INTO talumno (DNI_E, nombres, apellidos, sexo, celular, correo) VALUES ('"+dni+"','"+nombres+"','"+apellidos+"','"+sexo+"','"+celular+"','"+email+"')";
                    PreparedStatement ps=(PreparedStatement) cn.prepareStatement(consulta);
                    ps.executeUpdate();
                    limpiar(); // llama a metodo limpiar
                    jTabbedPane1.setSelectedIndex(5);
                    //JOptionPane.showMessageDialog(null,"DATOS GUARDADOS CORRECTAMENTE");
                } catch (Exception e){
                     JOptionPane.showMessageDialog(null,"NO SE PUDO GUARDAR USUARIO"+e);
                    
                }
            }
                
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        String grup=combotipog.getSelectedItem().toString();
        String turn=combotipot.getSelectedItem().toString();
        String ciclo=combotipoc.getSelectedItem().toString();
        String codi=txtNdni.getText();
        
        
       
        
        if(codi.isEmpty()){
          JOptionPane.showMessageDialog(null,"DEBE COMPLETAR LOS DATOS"); // manda mensaje cuando el formulario esta vacio
        }else{
            if(grup.equalsIgnoreCase("--------")|| turn.equalsIgnoreCase("--------") || ciclo.equalsIgnoreCase("--------")){
                JOptionPane.showMessageDialog(null,"DEBE SELECCIONAR LOS OPCIONES");
            }else{
                try{
                    String consulta="INSERT INTO tmatricula (grupo, turno, ciclo, codigoAlumno) VALUES ('"+grup+"','"+turn+"','"+ciclo+"','"+codi+"')";
                    PreparedStatement ps=(PreparedStatement) cn.prepareStatement(consulta);
                    ps.executeUpdate();
                    limpiar(); // llama a metodo limpiar
                  
                    JOptionPane.showMessageDialog(null," Realizaste tu matricula de manera exitosa");
                    jTabbedPane1.setSelectedIndex(0);
                } catch (Exception e){
                     JOptionPane.showMessageDialog(null,"NO SE PUDO GUARDAR USUARIO"+e);
                    
                }
               
            }
                
        }
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
     //elimanar  jLabel9.setBackground(new Color(242,230,255)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
     //eiminar  jLabel9.setBackground(new Color(214,180,248)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jLabel9VetoableChange
        //elimanar TODO add your handling code here:
    }//GEN-LAST:event_jLabel9VetoableChange

    private void txtMySexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMySexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMySexActionPerformed

    private void txtmiApelliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmiApelliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmiApelliActionPerformed

    private void TablaMisDatosEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMisDatosEstMouseClicked
       Modificar();  // TODO add your handling code here:
    }//GEN-LAST:event_TablaMisDatosEstMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
         ModificarMyDatos();
      
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMyContraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMyContraseMouseClicked
       ModificarContrasenia();
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMyContraseMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       ModificarMyContrase(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       dispose();  // la ventana anterior se cierra
       frmlogin dialog = new frmlogin(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    void limpiar(){ //borra despues de haber registrado
        txtdni.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        combotipo.getSelectedItem().toString();
        
        txtcelular.setText("");
        txtemail.setText("");
        
        combotipog.getSelectedItem().toString();
        combotipot.getSelectedItem().toString();
        combotipoc.getSelectedItem().toString();
        txtNdni.setText("");
        
    }
    
    //muestra edatos en la TablaMisDatosEst para editar
    void mostrarTablaEstud(){  
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("N° DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Sexo");
       
        modelo.addColumn("N° Celular");
        modelo.addColumn("E-mail");
        TablaMisDatosEst.setModel(modelo);
        
          String  sql="Select*from talumno where DNI_E  = '"+DNIusuarioLog+"'";

        String Usuario[]=new String[7];
        Statement set;
        
        try{
           set =(Statement) cn.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()){
                Usuario[0]=resul.getString(1);
                Usuario[1]=resul.getString(2);
                Usuario[2]=resul.getString(3);
                Usuario[3]=resul.getString(4);
                Usuario[4]=resul.getString(5);
                Usuario[5]=resul.getString(6);
                
                modelo.addRow(Usuario);
            }
           
        }catch(Exception e){
        System.out.println(e.getMessage());    
        //Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    public void Modificar(){
        int fila=TablaMisDatosEst.getSelectedRow();
        if(fila>=0){
            txtMyDNI.setText(TablaMisDatosEst.getValueAt(fila,0).toString());
            txtmiName.setText(TablaMisDatosEst.getValueAt(fila,1).toString());
            txtmiApelli.setText(TablaMisDatosEst.getValueAt(fila,2).toString());
            txtMySex.setText(TablaMisDatosEst.getValueAt(fila,3).toString());
            txtMyCell.setText(TablaMisDatosEst.getValueAt(fila,4).toString());
            txtMyCorreo.setText(TablaMisDatosEst.getValueAt(fila,5).toString());
            
                    
        }
        else{
            JOptionPane.showConfirmDialog(null,"Seleccione fila");
        }   
    }
    
    public void ModificarMyDatos(){
    
        try{
        PreparedStatement pasar=(PreparedStatement) cn.prepareStatement("Update talumno set nombres='"+txtmiName.getText()+""+
                "',apellidos='"+txtmiApelli.getText()+"',sexo='"+txtMySex.getText()+"',celular='"+txtMyCell.getText()+""+
                        "',correo='"+txtMyCorreo.getText()+"'where DNI_E='"+txtMyDNI.getText()+"'");
       pasar.executeUpdate();
       mostrarTablaEstud();
       
        }catch (SQLException ex) {
          
        }
    }
    
    //muestra la tabla para edicion de contraseña
    void mostrarTUsername(){  
        DefaultTableModel modelo=new DefaultTableModel();
        
       
        modelo.addColumn("USUARIO");
        modelo.addColumn("CONTRASEÑA");
      
        tableMyContrase.setModel(modelo);
        
          String  sql="SELECT u_dni, password FROM tusuario  WHERE u_dni = '"+DNIusuarioLog+"'";

        String Usuario[]=new String[3];
        Statement set;
        
        try{
           set =(Statement) cn.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()){
                Usuario[0]=resul.getString(1);
                Usuario[1]=resul.getString(2);
                
                
                modelo.addRow(Usuario);
            }
        }catch(Exception e){
        System.out.println(e.getMessage());    
        //Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    //////////////////////
     public void ModificarContrasenia(){
        int fila=tableMyContrase.getSelectedRow();
        if(fila>=0){
            
            txtaUsename.setText(tableMyContrase.getValueAt(fila,0).toString());
            txtUserContra.setText(tableMyContrase.getValueAt(fila,1).toString());
                   
        }
        else{
            JOptionPane.showConfirmDialog(null,"Seleccione fila");
        }   
    }
    
     //Modificar la contraseña de usuario
     public void ModificarMyContrase(){
    
        try{
        PreparedStatement pasar=(PreparedStatement) cn.prepareStatement("Update tusuario set password='"+txtUserContra.getText()+""+
                        "'where u_dni = '"+txtaUsename.getText()+"'");
       pasar.executeUpdate();
       mostrarTUsername();
       
        }catch (SQLException ex) {
          
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intranetEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intranetEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intranetEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intranetEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intranetEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pane1;
    private javax.swing.JPanel Pane2;
    private javax.swing.JPanel Pane3;
    private javax.swing.JPanel Pane4;
    private javax.swing.JPanel Pane5;
    private javax.swing.JPanel Pane6;
    private javax.swing.JTable TablaMisDatosEst;
    public javax.swing.JLabel activoUsuario;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JComboBox<String> combotipoc;
    private javax.swing.JComboBox<String> combotipog;
    private javax.swing.JComboBox<String> combotipot;
    private javax.swing.JLabel fonsup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableMyContrase;
    private javax.swing.JTextField txtMyCell;
    private javax.swing.JTextField txtMyCorreo;
    private javax.swing.JTextField txtMyDNI;
    private javax.swing.JTextField txtMySex;
    private javax.swing.JTextField txtNdni;
    private javax.swing.JTextField txtUserContra;
    private javax.swing.JTextField txtaUsename;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmiApelli;
    private javax.swing.JTextField txtmiName;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
